export const data = [
    {
        Id:0,
        title:"linkedIn",
        link:"www.linkedin.com/in/adel-hefny-75b6601bb"
    },
    {
        Id:1,
        title:"facebook",
        link:"www.facebook.com/"
    },
    {
        Id:2,
        title:"X",
        link:"twitter.com/"
    },
    {
        Id:3,
        title:"instagram",
        link:"www.instagram.com/"
    }
]